FEET_SCALE = 1

# Values in feet
FEET_PER_YARD = 3
YARDS_PER_LINE = 5
FIELD_SHAPE = 360 * FEET_SCALE, 160 * FEET_SCALE
NFL_HASH_MARK_MARGIN = 70.75 * FEET_SCALE
NCAAF_HASH_MARK_MARGIN = 60 * FEET_SCALE

NFL_HASH_MARK_YS = [NFL_HASH_MARK_MARGIN, FIELD_SHAPE[1] - NFL_HASH_MARK_MARGIN]
NCAAF_HASH_MARK_YS = [NCAAF_HASH_MARK_MARGIN, FIELD_SHAPE[1] - NCAAF_HASH_MARK_MARGIN]

YARD_LINE_MARGIN = 10 * FEET_PER_YARD * FEET_SCALE
YARD_LINE_XS = range(YARD_LINE_MARGIN, FIELD_SHAPE[0] - YARD_LINE_MARGIN + 1, FEET_PER_YARD * YARDS_PER_LINE * FEET_SCALE)
REFERENCE_XS = YARD_LINE_XS[10:]

NFL_REFERENCE_POINTS = [(x, y) for x in REFERENCE_XS for y in NFL_HASH_MARK_YS]
NCAAF_REFERENCE_POINTS = [(x, y) for x in REFERENCE_XS for y in NCAAF_HASH_MARK_YS]

REFERENCE_POINTS = {'NFL': NFL_REFERENCE_POINTS, 'NCAAF': NCAAF_REFERENCE_POINTS}

YARD_LINES = [[(x, x), (0, FIELD_SHAPE[1])] for x in YARD_LINE_XS]
HASH_LINES = {'NFL':    [[(0, FIELD_SHAPE[0]), (y, y)] for y in NFL_HASH_MARK_YS],
              'NCAAF':  [[(0, FIELD_SHAPE[0]), (y, y)] for y in NCAAF_HASH_MARK_YS]}
                       
YARD_LINE_COLOR = 'red'
HASH_LINE_COLOR = 'blue'

IMAGE_WIDTH = 320
IMAGE_HEIGHT = 180

OUTPUT_SHAPE = FIELD_SHAPE

# BL - BR - TR - TL
ORIGINAL_CORNERS = [(0, 0), (IMAGE_WIDTH, 0), (IMAGE_WIDTH, IMAGE_HEIGHT), (0, IMAGE_HEIGHT)]

NCAAF_TEAMS = ['Mountaineers', 'Hurricanes', 'Black Knights', 'MeanGreen', 'Razorbacks', 'Hokies']
NFL_TEAMS = ['Falcons', 'Packers']
